apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTVRFeApNRFEzTXpoYUZ3MDBNakEyTVRFeE1EUTNNemhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQm9lQzlVSHBTRmdEbUpGcmMxdWhKU2QyamMwb1FlM0cvVmJ4RFdGS0pIVzBENlNDRwpZeFRBNWFJYUNkUTV4eWRFVlZ1MFIrZk5DdGRFUUM4aklyQkJnYVpPbWdWeCtnc2dKTTRwYktnUG90aVVaR3JRCjdGRnMyQU5OQ0VHcVZxZzdQN2oxOW92N1pxWlNCZUUyTVpxU2FWdVViL1ZJdUN6MDBpNkdnWGFpWVRqakxlSXEKL0VETU50dXRWQTU4QnRuNm0yYVBWVnNmNW5XaHZvZVp1Snh4dFNHbjBmMy9WODVIaTlQd3RwQlBRc1RBT0ZVcgozWGltU2hFbk1MUTlrRklxQTZmUmp2UWRjRWptSkdaZ2lGL1p2WGhrcjdjUWtKTlNDOVlwa1prbGFua05QVkRTCkw0VEt6ZGdXTTIvd29hUSt1Uk1iZnBLaHRxVUpibEo5WWZkdEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRkZjZnR3h3bjZLaDRPUDN2UgpEakoydUcwU2ZEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFseFg0RWJaSXJodGVVQ0Jzd3pNRmxYS2dXQXVjCmxDNHpFM1RER04zQ1BLbDBLcjV5Zzc1d1R2NkVRdThSdkxvSGdTMXRjVHJxeS8wRzFBZ2ozb2VVMG5wWWNQNzIKZm01czZsYU9hajBEelBVNTg1ZXIzbWx5TTFocFptNEpWcDRmNlpFVFE3S1RZSFYvOGxBd0ZTR1VDVVE3eE1oeQpyNzN0TGF0UGh4aWlzSWlIcGVUYStzdm53NjRFZ0d1NDJ6VmtSS3hTQndZK2NLbHlKOVVZaTVkYWtCaUpJRHI4CmpmN0pRNDVHZ1NUYXRNQWIvQzdrVm5XcVpPbHVQOWttYmIxNFdDUUVrUW5VUnNJUHNFejZHRnJrY1ZlQXRXSzEKc3NkMjZYc0FzK2JnM0NqWUk0MlhoRU5sVlN4QWZnR00wUHBCMytLSEdveDhQRFhOazczbDh2eE9UQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e5f1d5c7-8f90-46d6-81d4-bc34366429e4.k8s.ondigitalocean.com
  name: do-nyc1-k8s-teste
contexts:
- context:
    cluster: do-nyc1-k8s-teste
    user: do-nyc1-k8s-teste-admin
  name: do-nyc1-k8s-teste
current-context: do-nyc1-k8s-teste
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-teste-admin
  user:
    token: dop_v1_5c01891c524603ab8eca7b8b7a5400dc885e5d5142caad18b5cb014d71f02435
